name: CanKey

on:
  repository_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: git clone https://github.com/Nanonona/canokey-management-tool
    - run: cd canokey-management-tool && flutter pub get
    - run: cd canokey-management-tool && flutter build web

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: web
        path: ${{ github.workspace }}/canokey-management-tool/build/web*

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: web
        FOLDER: ${{ github.workspace }}/canokey-management-tool/build/web
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
